https://github.com/Chief1934/SATOSHI.wiki.gitEIP-170 issue and discussion: https://github.com/ethereum/EIPs/issues/170
pyethereum implementation: https://github.com/ethereum/pyethereum/blob/5217294871283d8dc4fb3ca9d8a78c7d416490e8/ethereum/messages.py#L397
Citation
Please cite this document as:

Vitalik Buterin (@vbuterin), "EIP-170: Contract https://github.com/ethereum/EIPs/issues/170https://github.com/Chief1934/SATOSHI.wiki.gitEIP-170 issue and discussion: https://github.com/ethereum/EIPs/issues/170
pyethereum implementation: https://github.com/ethereum/pyethereum/blob/5217294871283d8dc4fb3ca9d8a78c7d416490e8/ethereum/messages.py#L397
Citation
Please cite this document as:

Vitalik Buterin (@vbuterin), "EIP-170: Contract https://github.com/ethereum/pyethereum/blob/5217294871283d8dc4fb3ca9d8a78c7d416490e8/ethereum/messages.py#L397# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
